[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "mariana", email = "marianafariasss590@gmail.com"},
]
dependencies = [
    "django>=4.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
