# Generated by Django 4.2.4 on 2023-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0004_remove_veiculo_categoria_remove_veiculo_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='capa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capa',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
    ]
